# -*- coding: utf-8 -*-
{
    'name': "Phidias Document Formation",
    'summary': """
        Phidias : specifique Document Formation
        """,
    'description': """
        Document de gestion des formations
    """,

    'author': "Phidias",
    'website': "http://www.phidias.fr",
    'category': 'Uncategorized',
    'version': '16.0.0.48',

    # any module necessary for this one to work correctly
    'depends': ['sale'],
    "data": [
        "security/ir.model.access.csv",
        "views/account_invoice_views.xml",
        "views/mail_template_view.xml",
        "views/eval_acquis.xml",
        "views/formation_partner_inherit.xml",
        "views/version_odoo.xml",
        "views/formations_menu_views.xml",
        "views/formations_participants_view.xml",
        "views/product_view.xml",
        "views/Programme_formation.xml",
        "views/automated_action.xml",
        "views/fiche_emargement_view.xml",
        "views/acces_view.xml",
        "views/dossier_formations_view.xml",
        "views/sale_order_views.xml",
        "views/support_formations_view.xml",
        "views/demande_formations_view.xml",
        "views/formations_pre_requis_view.xml",
        "views/fiche_reclamation_view.xml",
        "views/formations_compte_rendu_view.xml",
        "wizard/formation_lost_views.xml",
        "wizard/session_lost_views.xml",
        "wizard/formation_postponed_views.xml",
        "data/mail_template_data.xml",
        "data/mail_survey_inherit.xml",
        "data/mail_template_distance.xml",
        "data/mail_template_support_formation.xml",
        "data/mail_plan_formation.xml",
        "data/mail_template_acces_formation.xml",
        "data/mail_pre_requis.xml",
        "data/mail_eval_chaud.xml",
        "data/mail_eval_froid.xml",
        "data/mail_eval_global.xml",
        "data/mail_plan_formation_bis.xml",
        "views/formations_report.xml",
        "views/formations_eval_view.xml",
        "views/formations_eval_chaud_view.xml",
        "views/formations_eval_global_view.xml",
        "views/formation_sessions_report.xml",
        "views/formations_modules_view.xml",
        "views/res_partner_views.xml",
        "views/search_contact_inherit_views.xml",
        "views/lost_reason_view.xml",
        "views/sign_views_inherit.xml",
        "views/survery_views.xml",
        "views/res_partner_views.xml",
        "views/survey_user_input_view_list_inherit.xml",
        "views/survey_survey_views.xml",
        "views/plan_formation_views.xml",
    ],

}
