from . import formations_report2
from . import formations_sessions
from . import formations_eval
from . import formations_modules
from . import formations_eval_chaud
from . import formations_eval_global
from . import dossier_formations
from . import demande_formations
from . import formations_pre_requis
from . import fiche_reclamation
from . import formations_compte_rendu
from . import support_formations
from . import formations_participants
from . import fiche_emargement
from . import acces
from . import sale_order
from . import product
from . import account_move
from . import version_odoo
from . import eval_acquis
from . import formation_partner
from . import sign
from . import survey
from . import res_partner_inherit_models
from . import plan_formation
from . import programme_formation